######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 1 17:03:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h thread.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp thread.cpp
